### PR TITLE
Dokka upgrade

### PR DESCRIPTION
**Pull request by jamowei**
- Upgraded version of Dokka to newest version
- added multiproject Dokka task for core, styling & components

### CODE REVIEW

**Comment by chausknecht** [comment]
It still builds and everything gets into /api.
But I don't see any visible changes within the HTML documentation itself. The customization seems not to wqork yet.

**Comment by jamowei** [comment]
The changes will only be available after we pulished the new fritz2 version 0.8.

**Comment by chausknecht** [comment]
As the main testable part works (building) , I think we should close this :-)

**Comment by chausknecht** [comment]
Looks good to me!

**Review by chausknecht — DISMISSED** [review]

**Review by chausknecht — APPROVED** [review]

**Pull request merged**
