### PR TITLE
Update broken references

### PR DESCRIPTION
**Pull request by emmanuel-ferdman**
# PR Summary
Commit fdbf998ac23026658c37a5e37610648642ed1592 renamed bunch of Java files. This PR adjusts sources to changes.

### CODE REVIEW

**Review by haukesomm — APPROVED** [review]
Hi, thanks for contributing! Everything looks good here, approved

**Review by haukesomm — CHANGES_REQUESTED** [review]
It's me again, I'm sorry to revoke my approval but there is one more referenace in the documentation/blog that seems to be broken:

- `www/src/blog/posts/paradigm-shift-for-components.md`, line 266
  - `https://github.com/jwstegemann/fritz2/blob/master/headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/radioGroup.kt`

Would you mind fixing that one as well? this way, we can avoid another PR for just one line of code 😄 

Thanks!

**Comment by emmanuel-ferdman** [comment]
@haukesomm sure thing, please let me know if anything else is needed from my side 😄

**Review by haukesomm — APPROVED** [review]
Tranks, everything Looks good once again!

**Pull request merged**
