### PR TITLE
Change type of ``RenderContext`` to make it an universal receiver for rendering

### PR DESCRIPTION
**Pull request by chausknecht**
- solves #228
- make ``RenderContext`` a type alias for ``Tag<HtmlElements>`` in order to make it a fitting and universal receiver type for rendering
- all components should not need changes, as they accidentally yet refer to this currently false type
- need to test all example projects too!

### CODE REVIEW

**Comment by chausknecht** [comment]
Ignore the commit message! (Has been in cache and used accidentally!)!
There is no work done yet! Just added a comment in order to be able to create this PR.

**Comment by chausknecht** [comment]
I have allready tested the changes with our kitchensink project; I have not found any errors or different behaviours!

**Comment by jamowei** [comment]
I have discovered only one problem in Webcomponents API because there is something like this:
```kotlin
@ExperimentalCoroutinesApi
@JsName("WebComponent")
abstract class WebComponent<T : Element>(observeAttributes: Boolean = true) {
    @JsName("init")
    abstract fun init(element: HTMLElement, shadowRoot: ShadowRoot): Tag<T>
...
}
```
But currently there is no function for creating `Tag`s anymore.
That is why I used a workaround in `webcomponents.kt` tests wich must be fixed:
```kotlin
//FIXME: use RenderContext instead!
inline fun <E : Element> createTag(content: HtmlElements.() -> Tag<E>): Tag<E> =
    content(object : HtmlElements {
        override val job = Job()
        override fun <E : Element, T : WithDomNode<E>> register(element: T, content: (T) -> Unit): T {
            content(element)
            return element
        }
    })

class MyComponent : WebComponent<HTMLParagraphElement>() {
    override fun init(element: HTMLElement, shadowRoot: ShadowRoot) =
        createTag {
            p(id = "paragraph-in-web-component") {
                +"I am a WebComponent"
            }
        }
}
```
@jwstegemann do you have any idea?

**Comment by jamowei** [comment]
@chausknecht can you review the `modal.kt` and `theme.kt` especially.

**Comment by jamowei** [comment]
@chausknecht now you can replace all `HtmlElements` with `RenderContext` in `compontents` project. ;)

**Comment by chausknecht** [comment]
> 
> 
> @chausknecht can you review the `modal.kt` and `theme.kt` especially.

Done. Just added one render function variant for the theme (provide the ID instead of an HtmlElement) and minor documentation and readability changes.

**Comment by chausknecht** [comment]
> 
> 
> @chausknecht now you can replace all `HtmlElements` with `RenderContext` in `compontents` project. ;)

Done.
Tested changes with KitchenSink project - besides adapting the new render function API to KitchenSink's main render function call, everything works like charm!

**Review by jwstegemann — APPROVED** [review]
great work!

**Pull request merged**
