### PR TITLE
upgrade to kotlin 1.7 & other dependency updates

### PR DESCRIPTION
**Pull request by jillesvangurp**
upgrades to kotlin 1.6.21

fix ksp related things in the build (a few things changed in ksp)

Tests seem to pass.

### CODE REVIEW

**Comment by jillesvangurp** [comment]
fixes #636

**Comment by chausknecht** [comment]
As 1.7 is out, we should upgrade directly to 1.7.

I would propose to wait for PR #644 to be accomplished and then try to update this PR towards 1.7. Armed with the unit- and ui-tests we should be quite save to do that move now.

**Comment by chausknecht** [comment]
@jillesvangurp Thank you! We will investigate this PR very soon. Right now I focus on the UI tests in order to have them in place before upgrading to 1.7. Stay tuned for questions or the finished RC1 :-)

**Comment by chausknecht** [comment]
You are right. Bu as you have stated already, that ksp has introduced some changes, I believe we will be safer to do the "major" move to 1.7 directly and investigate carefully, what we must change for out template projects and what we should document as migration help.

We are very close to the RC1 release, so even such minimal looking aspects could disturb the release.

But your PR will not be forgotten! :-)

**Comment by jwstegemann** [comment]
I just merged our 1.0-RC1 master into this branch, set coroutines-dependency to 1.6.3 (which fixes the error that @jillesvangurp mentioned above) and added a workaround for a broken webpack-cli-dependency with kotlin 1.7.
Works for me like a charm (recognizable performance gains at compile- and runtime).

**Comment by jwstegemann** [comment]
Would be happy about some more tests (especially of the build on some other operating-systems and hardware)

**Comment by jillesvangurp** [comment]
I'll give it a try early next week.

**Comment by jamowei** [comment]
Successfully tested this PR under Linux/Ubuntu:
- [x] ./gradlew build
- [x] playwright tests
👍🏻

**Review by jamowei — APPROVED** [review]

**Comment by jwstegemann** [comment]
Just added to new Branches to the template-projects to work with this version:

https://github.com/jwstegemann/fritz2-template/pull/14
https://github.com/jwstegemann/fritz2-tailwind-template/pull/2

**Pull request merged**
