### PR TITLE
Update to Kotlin 1.8.22 and other libraries

### PR DESCRIPTION
**Pull request by serras**

### CODE REVIEW

**Review by jamowei — APPROVED** [review]
Thanks!

**Comment by Lysander** [comment]
There might be some places in the docs, where we refer to the kotlin-version - I think those might be adopted too.

**Comment by serras** [comment]
Note that updating the Kotlin version is required for #787 to work, so the sooner this is merged into `master`, the better (if you want that PR to work, of course).

**Comment by serras** [comment]
> There might be some places in the docs, where we refer to the kotlin-version - I think those might be adopted too.

The latest commit updates the references in the docs too.

**Comment by Lysander** [comment]
We need some RC8-Release with PR #781 before we upgrade the Kotlin version due to some internal projects, that need this with the current Kotlin version.

I think on Monday we should be able to build the RC and after that, we can merge this one.

**Comment by jamowei** [comment]
Closed in favor of #789

**Pull request closed without merging**
